# Site settings
title: Joenio Costa
email: joenio@colivre.coop.br
baseurl: ""
url: "http://joenio.me"
twitter_username: joenio
github_username:  joenio

# Build settings
markdown: kramdown
permalink: ":title"

# Nao copie estes arquivos para _site
exclude:
  - README.markdown
  - script
  - samples

# Configuracoes padrao para posts
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
  -
    scope:
      path: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "slides"
    values:
      layout: "slide"
