# Site settings
title: Joenio Costa
email: joenio@colivre.coop.br
baseurl: ""
url: "http://joenio.me"
twitter_username: joenio
github_username: joenio

# Build settings
markdown: kramdown
permalink: ":title/index.html"

# Opcoes para kramdown
kramdown:
  parse_block_html: true

# Nao copie estes arquivos para _site
exclude:
  - README.markdown
  - script
  - samples

# Nao apague estes arquivos ao executar build
keep_files:
  - .git
  - .svn
  - javascript

# Configuracoes padrao para posts
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
  -
    scope:
      path: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "slides"
    values:
      layout: "revealjs"
